# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    #runs-on: macos-latest
    runs-on:	macos-13

    steps:
    - uses: actions/checkout@v4
    - name: install Homebrew
      run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    - name: install Theos
      #run: bash -c "$(curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos)"
      run: |
          chmod +x /Users/runner/work/Geranium/Geranium/intall_theos.sh
          bash -c /Users/runner/work/Geranium/Geranium/intall_theos.sh
    - name: start build
      run: |
          chmod +x /Users/runner/work/Geranium/Geranium/ipabuild.sh
          cd /Users/runner/work/Geranium/Geranium
          ./ipabuild.sh
